// import { RRule } from "rrule";
import { ProcessedEvent } from "./lib/types";

// export const EVENTS: ProcessedEvent[] = [
//   {
//     event_id: 1,
//     title: "Event 1 (Disabled)",
//     subtitle: "This event is disabled",
//     start: new Date(new Date(new Date().setHours(9)).setMinutes(0)),
//     end: new Date(new Date(new Date().setHours(10)).setMinutes(0)),
//     disabled: true,
//     admin_id: [1, 2, 3, 4],
//   },
//   {
//     event_id: 2,
//     title: "Event 2",
//     subtitle: "This event is draggable",
//     start: new Date(new Date(new Date().setHours(10)).setMinutes(0)),
//     end: new Date(new Date(new Date().setHours(12)).setMinutes(0)),
//     admin_id: 2,
//     color: "#50b500",
//     agendaAvatar: "E",
//   },
//   {
//     event_id: 3,
//     title: "Event 3",
//     subtitle: "This event is not editable",
//     start: new Date(new Date(new Date().setHours(11)).setMinutes(0)),
//     end: new Date(new Date(new Date().setHours(12)).setMinutes(0)),
//     admin_id: 1,
//     editable: false,
//     deletable: false,
//   },
//   {
//     event_id: 4,
//     title: "Event 4",
//     start: new Date(
//       new Date(new Date(new Date().setHours(9)).setMinutes(30)).setDate(new Date().getDate() - 2)
//     ),
//     end: new Date(
//       new Date(new Date(new Date().setHours(11)).setMinutes(0)).setDate(new Date().getDate() - 2)
//     ),
//     admin_id: [2, 3],
//     color: "#900000",
//     allDay: true,
//   },
//   {
//     event_id: 5,
//     title: "Event 5",
//     subtitle: "This event is editable",
//     start: new Date(
//       new Date(new Date(new Date().setHours(10)).setMinutes(30)).setDate(new Date().getDate() - 2)
//     ),
//     end: new Date(
//       new Date(new Date(new Date().setHours(14)).setMinutes(0)).setDate(new Date().getDate() - 2)
//     ),
//     admin_id: 2,
//     editable: true,
//   },
//   {
//     event_id: 6,
//     title: "Event 6",
//     subtitle: "This event is all day",
//     start: new Date(
//       new Date(new Date(new Date().setHours(20)).setMinutes(30)).setDate(new Date().getDate() - 3)
//     ),
//     end: new Date(new Date(new Date().setHours(23)).setMinutes(0)),
//     admin_id: 2,
//     allDay: true,
//     sx: { color: "purple" },
//   },
//   {
//     event_id: 7,
//     title: "Event 7 (Not draggable)",
//     subtitle: "This event is not draggable",
//     start: new Date(
//       new Date(new Date(new Date().setHours(10)).setMinutes(30)).setDate(new Date().getDate() - 3)
//     ),
//     end: new Date(
//       new Date(new Date(new Date().setHours(14)).setMinutes(30)).setDate(new Date().getDate() - 3)
//     ),
//     admin_id: 1,
//     draggable: false,
//     color: "#8000cc",
//   },
//   {
//     event_id: 8,
//     title: "Event 8",
//     subtitle: "This event has a custom color",
//     start: new Date(
//       new Date(new Date(new Date().setHours(10)).setMinutes(30)).setDate(new Date().getDate() + 30)
//     ),
//     end: new Date(
//       new Date(new Date(new Date().setHours(14)).setMinutes(30)).setDate(new Date().getDate() + 30)
//     ),
//     admin_id: 1,
//     color: "#8000cc",
//   },
//   {
//     event_id: 9,
//     title: "Event 9",
//     subtitle: `This event is a recurring weekly until ${new Date(
//       new Date().setMonth(
//         new Date(
//           new Date(new Date(new Date().setHours(11)).setMinutes(0)).setDate(
//             new Date().getDate() + 1
//           )
//         ).getMonth() + 1
//       )
//     ).toDateString()}`,
//     start: new Date(
//       new Date(new Date(new Date().setHours(10)).setMinutes(0)).setDate(new Date().getDate() + 1)
//     ),
//     end: new Date(
//       new Date(new Date(new Date().setHours(11)).setMinutes(0)).setDate(new Date().getDate() + 1)
//     ),
//     recurring: new RRule({
//       freq: RRule.WEEKLY,
//       dtstart: new Date(
//         new Date(new Date(new Date().setHours(10)).setMinutes(0)).setDate(new Date().getDate() + 1)
//       ),
//       until: new Date(
//         new Date().setMonth(
//           new Date(
//             new Date(new Date(new Date().setHours(11)).setMinutes(0)).setDate(
//               new Date().getDate() + 1
//             )
//           ).getMonth() + 1
//         )
//       ),
//     }),
//   },
//   {
//     event_id: 10,
//     title: "Event 10",
//     subtitle: "This event is a recurring hourly 3 times",
//     start: new Date(new Date(new Date().setHours(14)).setMinutes(15)),
//     end: new Date(new Date(new Date().setHours(14)).setMinutes(45)),
//     recurring: new RRule({
//       freq: RRule.HOURLY,
//       count: 3,
//       dtstart: new Date(new Date(new Date().setHours(14)).setMinutes(15)),
//     }),
//     color: "#dc4552",
//   },
// ];

export const RESOURCES = [
  {
    admin_id: 1,
    title: "One",
    mobile: "555666777",
    avatar: "",
    color: "#ab2d2d",
  },
  {
    admin_id: 2,
    title: "Two is very long name",
    mobile: "555666777",
    avatar: "https://picsum.photos/200/300",
    color: "#58ab2d",
  },
  {
    admin_id: 3,
    title: "Three",
    mobile: "555666777",
    avatar: "https://picsum.photos/200/300",
    color: "#a001a2",
  },
  {
    admin_id: 4,
    title: "Four",
    mobile: "555666777",
    avatar: "https://picsum.photos/200/300",
    color: "#08c5bd",
  },
];

export const EVENTS: ProcessedEvent[] = [
  {
    event_id: 56252,
    start: new Date("2025-01-23T00:00:00.000Z"),
    end: new Date("2025-01-23T00:00:00.000Z"),
    title: "Quiamno, Christine Cyril C. on Unpaid Leave for 1.0 Day/s: t",
    employee_number: "",
    name: "Quiamno, Christine Cyril C. on Unpaid Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 55892,
    start: new Date("2024-12-31T00:00:00.000Z"),
    end: new Date("2024-12-31T00:00:00.000Z"),
    title: "Garcia, Domiel Joy II D. on Vacation Leave for 1.0 Day/s: Mom's BDAY",
    employee_number: "",
    name: "Garcia, Domiel Joy II D. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47745,
    start: new Date("2024-12-31T00:00:00.000Z"),
    end: new Date("2024-12-31T00:00:00.000Z"),
    title: "Sarmiento, Maria Fides C. on Vacation Leave for 1.0 Day/s: Vacation Leave #14",
    employee_number: "",
    name: "Sarmiento, Maria Fides C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 46838,
    start: new Date("2024-12-31T00:00:00.000Z"),
    end: new Date("2024-12-31T00:00:00.000Z"),
    title:
      "Cervantes, Giovanni Dacillo on Vacation Leave for 1.0 Day/s: VL NEW YEAR  with  family ",
    employee_number: "",
    name: "Cervantes, Giovanni Dacillo on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 25700,
    start: new Date("2024-12-31T00:00:00.000Z"),
    end: new Date("2024-12-31T00:00:00.000Z"),
    title: "Special Holiday: Last day of the year",
    employee_number: "",
    name: "Last day of the year",
    holiday_type: "type_wpublic_holiday",
    category_ids: [2],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 25696,
    start: new Date("2024-12-30T00:00:00.000Z"),
    end: new Date("2024-12-30T00:00:00.000Z"),
    title: "Regular Holiday: Rizal Day",
    employee_number: "",
    name: "Rizal Day",
    holiday_type: "type_public_holiday",
    category_ids: [2],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 52772,
    start: new Date("2024-12-29T00:00:00.000Z"),
    end: new Date("2024-12-29T00:00:00.000Z"),
    title: "Bito, Cassandra Nicole P. on Vacation Leave for 1.0 Day/s: vl Dec. 29, Jan. 1 to 3.",
    employee_number: "",
    name: "Bito, Cassandra Nicole P. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47569,
    start: new Date("2024-12-29T00:00:00.000Z"),
    end: new Date("2024-12-31T00:00:00.000Z"),
    title: "Edoloverio, Jerrylyn P. on Vacation Leave for 3.0 Day/s: My Birthday",
    employee_number: "",
    name: "Edoloverio, Jerrylyn P. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 54406,
    start: new Date("2024-12-28T00:00:00.000Z"),
    end: new Date("2024-12-29T00:00:00.000Z"),
    title:
      "Ventusa, Julius Ray B. on Vacation Leave for 2.0 Day/s: Go visit the province and sons birthday",
    employee_number: "",
    name: "Ventusa, Julius Ray B. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 48004,
    start: new Date("2024-12-28T00:00:00.000Z"),
    end: new Date("2024-12-30T00:00:00.000Z"),
    title: "Lazaro, Philippe Ariel J. on Vacation Leave for 3.0 Day/s: VL December💍",
    employee_number: "",
    name: "Lazaro, Philippe Ariel J. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 44837,
    start: new Date("2024-12-28T00:00:00.000Z"),
    end: new Date("2024-12-30T00:00:00.000Z"),
    title: "Lazaro, Philippe Ariel J. on Vacation Leave for 3.0 Day/s: December VL",
    employee_number: "",
    name: "Lazaro, Philippe Ariel J. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47743,
    start: new Date("2024-12-27T00:00:00.000Z"),
    end: new Date("2024-12-28T00:00:00.000Z"),
    title: "Sarmiento, Maria Fides C. on Vacation Leave for 2.0 Day/s: Vacation Leave 12 & 13",
    employee_number: "",
    name: "Sarmiento, Maria Fides C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 56129,
    start: new Date("2024-12-25T00:00:00.000Z"),
    end: new Date("2024-12-31T00:00:00.000Z"),
    title: "Lumberio, Kimberly Daarol on Vacation Leave for 5.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Lumberio, Kimberly Daarol on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 25695,
    start: new Date("2024-12-25T00:00:00.000Z"),
    end: new Date("2024-12-25T00:00:00.000Z"),
    title: "Regular Holiday: Christmas Day",
    employee_number: "",
    name: "Christmas Day",
    holiday_type: "type_public_holiday",
    category_ids: [2],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 52856,
    start: new Date("2024-12-24T00:00:00.000Z"),
    end: new Date("2024-12-31T00:00:00.000Z"),
    title: "Dela Paz, Maria Carina M. on Vacation Leave for 8.0 Day/s: Vacation",
    employee_number: "",
    name: "Dela Paz, Maria Carina M. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 25704,
    start: new Date("2024-12-24T00:00:00.000Z"),
    end: new Date("2024-12-24T00:00:00.000Z"),
    title: "Special Holiday: Christmas Eve",
    employee_number: "",
    name: "Christmas Eve",
    holiday_type: "type_wpublic_holiday",
    category_ids: [2],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 44242,
    start: new Date("2024-12-17T00:00:00.000Z"),
    end: new Date("2024-12-17T00:00:00.000Z"),
    title: "Escallar, Joshua Dave L. on Vacation Leave for 1.0 Day/s: Father's bday",
    employee_number: "",
    name: "Escallar, Joshua Dave L. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 54127,
    start: new Date("2024-12-14T00:00:00.000Z"),
    end: new Date("2024-12-16T00:00:00.000Z"),
    title: "Gambito, Sabine Kristienne G. on Vacation Leave for 1.0 Day/s: BDAY LEAVE",
    employee_number: "",
    name: "Gambito, Sabine Kristienne G. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47075,
    start: new Date("2024-12-14T00:00:00.000Z"),
    end: new Date("2024-12-15T00:00:00.000Z"),
    title: "Yabis, Francis S. on Vacation Leave for 2.0 Day/s: vacation leave",
    employee_number: "",
    name: "Yabis, Francis S. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 42547,
    start: new Date("2024-12-14T00:00:00.000Z"),
    end: new Date("2024-12-18T00:00:00.000Z"),
    title: "Cajis, Ma. Angelica on Vacation Leave for 2.0 Day/s: VL December (IMPORTANT)",
    employee_number: "",
    name: "Cajis, Ma. Angelica on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 46772,
    start: new Date("2024-12-09T00:00:00.000Z"),
    end: new Date("2024-12-11T00:00:00.000Z"),
    title: "Gabelenio, Alexis Owen S. on Vacation Leave for 3.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Gabelenio, Alexis Owen S. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 46742,
    start: new Date("2024-12-08T00:00:00.000Z"),
    end: new Date("2024-12-11T00:00:00.000Z"),
    title: "Olaes, Jodelyn F. on Vacation Leave for 4.0 Day/s: Vacation Leave ",
    employee_number: "",
    name: "Olaes, Jodelyn F. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 25699,
    start: new Date("2024-12-08T00:00:00.000Z"),
    end: new Date("2024-12-08T00:00:00.000Z"),
    title: "Special Holiday: Feast of the Immaculate Conception of Mary",
    employee_number: "",
    name: "Feast of the Immaculate Conception of Mary",
    holiday_type: "type_wpublic_holiday",
    category_ids: [2],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 56240,
    start: new Date("2024-12-05T00:00:00.000Z"),
    end: new Date("2024-12-05T00:00:00.000Z"),
    title: "Quiamno, Christine Cyril C. on Unpaid Leave for 1.0 Day/s: t",
    employee_number: "",
    name: "Quiamno, Christine Cyril C. on Unpaid Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 52959,
    start: new Date("2024-12-02T00:00:00.000Z"),
    end: new Date("2024-12-06T00:00:00.000Z"),
    title: "Tajanlangit, Jerald David Confesor on Vacation Leave for 5.0 Day/s: VACATION LEAVE",
    employee_number: "",
    name: "Tajanlangit, Jerald David Confesor on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 25694,
    start: new Date("2024-11-30T00:00:00.000Z"),
    end: new Date("2024-11-30T00:00:00.000Z"),
    title: "Regular Holiday: Bonifacio Day",
    employee_number: "",
    name: "Bonifacio Day",
    holiday_type: "type_public_holiday",
    category_ids: [2],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 54113,
    start: new Date("2024-11-29T00:00:00.000Z"),
    end: new Date("2024-11-29T00:00:00.000Z"),
    title: "Noriega, Reeve Tyron P. on Vacation Leave for 1.0 Day/s: Vacation Leave #4",
    employee_number: "",
    name: "Noriega, Reeve Tyron P. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 43871,
    start: new Date("2024-11-26T00:00:00.000Z"),
    end: new Date("2024-11-28T00:00:00.000Z"),
    title: "Edanggalino, Angel F. on Vacation Leave for 3.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Edanggalino, Angel F. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 46377,
    start: new Date("2024-11-25T00:00:00.000Z"),
    end: new Date("2024-11-25T00:00:00.000Z"),
    title: "Santos, Raphael Daniel C. on Vacation Leave for 1.0 Day/s: VL",
    employee_number: "",
    name: "Santos, Raphael Daniel C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 54112,
    start: new Date("2024-11-24T00:00:00.000Z"),
    end: new Date("2024-11-24T00:00:00.000Z"),
    title: "Noriega, Reeve Tyron P. on Vacation Leave for 1.0 Day/s: Vacation Leave #3",
    employee_number: "",
    name: "Noriega, Reeve Tyron P. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 56250,
    start: new Date("2024-11-23T00:00:00.000Z"),
    end: new Date("2024-11-23T00:00:00.000Z"),
    title: "Quiamno, Christine Cyril C. on Maternity Leave for 1.0 Day/s: t",
    employee_number: "",
    name: "Quiamno, Christine Cyril C. on Maternity Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 55693,
    start: new Date("2024-11-23T00:00:00.000Z"),
    end: new Date("2024-11-25T00:00:00.000Z"),
    title: "Denoy, John Lloyd C. on Vacation Leave for 3.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Denoy, John Lloyd C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 52770,
    start: new Date("2024-11-23T00:00:00.000Z"),
    end: new Date("2024-11-23T00:00:00.000Z"),
    title: "Liatona, Christine L. on Vacation Leave for 1.0 Day/s: Vacation",
    employee_number: "",
    name: "Liatona, Christine L. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 46411,
    start: new Date("2024-11-22T00:00:00.000Z"),
    end: new Date("2024-11-24T00:00:00.000Z"),
    title: "Aransazo, Frances Thea A. on Vacation Leave for 2.0 Day/s: VACATION LEAVE - 2 DAYS",
    employee_number: "",
    name: "Aransazo, Frances Thea A. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 43864,
    start: new Date("2024-11-22T00:00:00.000Z"),
    end: new Date("2024-11-23T00:00:00.000Z"),
    title: "Ambrocio, Allen E. on Vacation Leave for 2.0 Day/s: VL",
    employee_number: "",
    name: "Ambrocio, Allen E. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 49588,
    start: new Date("2024-11-21T00:00:00.000Z"),
    end: new Date("2024-11-26T00:00:00.000Z"),
    title: "Sabarita, Gerry Lynn on Vacation Leave for 6.0 Day/s: Family Birthday",
    employee_number: "",
    name: "Sabarita, Gerry Lynn on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47022,
    start: new Date("2024-11-21T00:00:00.000Z"),
    end: new Date("2024-11-24T00:00:00.000Z"),
    title: "Gelotin, Geneva E. on Vacation Leave for 4.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Gelotin, Geneva E. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 44975,
    start: new Date("2024-11-21T00:00:00.000Z"),
    end: new Date("2024-11-26T00:00:00.000Z"),
    title: "Magada, Randolf G. on Vacation Leave for 4.0 Day/s: CMU Trail Race",
    employee_number: "",
    name: "Magada, Randolf G. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 55874,
    start: new Date("2024-11-20T00:00:00.000Z"),
    end: new Date("2024-11-23T00:00:00.000Z"),
    title: "Murillo, Mary Ann G. on Vacation Leave for 4.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Murillo, Mary Ann G. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 43852,
    start: new Date("2024-11-19T00:00:00.000Z"),
    end: new Date("2024-11-21T00:00:00.000Z"),
    title: "Yalung, Jenico Edel T. on Vacation Leave for 3.0 Day/s: Vl",
    employee_number: "",
    name: "Yalung, Jenico Edel T. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47263,
    start: new Date("2024-11-18T00:00:00.000Z"),
    end: new Date("2024-11-18T00:00:00.000Z"),
    title: "Gaba, Alyssa Michele C. on Vacation Leave for 1.0 Day/s: VL -",
    employee_number: "",
    name: "Gaba, Alyssa Michele C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 53780,
    start: new Date("2024-11-17T00:00:00.000Z"),
    end: new Date("2024-11-18T00:00:00.000Z"),
    title: "Santiago, Zuleika Dea T. on Vacation Leave for 2.0 Day/s: VL",
    employee_number: "",
    name: "Santiago, Zuleika Dea T. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 54477,
    start: new Date("2024-11-16T00:00:00.000Z"),
    end: new Date("2024-11-16T00:00:00.000Z"),
    title: "Casera, Blanchie M. on Vacation Leave for 1.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Casera, Blanchie M. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 52771,
    start: new Date("2024-11-16T00:00:00.000Z"),
    end: new Date("2024-11-17T00:00:00.000Z"),
    title: "Bito, Cassandra Nicole P. on Vacation Leave for 2.0 Day/s: vl Nov. 16 to Nov. 17",
    employee_number: "",
    name: "Bito, Cassandra Nicole P. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 55169,
    start: new Date("2024-11-15T00:00:00.000Z"),
    end: new Date("2024-11-19T00:00:00.000Z"),
    title: "Bascones, Candelle Vinace B. on Vacation Leave for 5.0 Day/s: VL",
    employee_number: "",
    name: "Bascones, Candelle Vinace B. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 48565,
    start: new Date("2024-11-15T00:00:00.000Z"),
    end: new Date("2024-11-19T00:00:00.000Z"),
    title: "Tabisora, Jessan Marie D. on Vacation Leave for 2.0 Day/s: VACATION LEAVE",
    employee_number: "",
    name: "Tabisora, Jessan Marie D. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47385,
    start: new Date("2024-11-15T00:00:00.000Z"),
    end: new Date("2024-11-16T00:00:00.000Z"),
    title: "Alfiler, Lorraine Anne R. on Vacation Leave for 2.0 Day/s: VL",
    employee_number: "",
    name: "Alfiler, Lorraine Anne R. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 46572,
    start: new Date("2024-11-15T00:00:00.000Z"),
    end: new Date("2024-11-19T00:00:00.000Z"),
    title: "Tabisora, Jessan Marie D. on Vacation Leave for 2.0 Day/s: VACATION LEAVE",
    employee_number: "",
    name: "Tabisora, Jessan Marie D. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 44963,
    start: new Date("2024-11-15T00:00:00.000Z"),
    end: new Date("2024-11-15T00:00:00.000Z"),
    title: "Santos, Raphael Daniel C. on Vacation Leave for 1.0 Day/s: VL",
    employee_number: "",
    name: "Santos, Raphael Daniel C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 54125,
    start: new Date("2024-11-14T00:00:00.000Z"),
    end: new Date("2024-11-16T00:00:00.000Z"),
    title: "Gambito, Sabine Kristienne G. on Vacation Leave for 1.0 Day/s: VL",
    employee_number: "",
    name: "Gambito, Sabine Kristienne G. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 54058,
    start: new Date("2024-11-13T00:00:00.000Z"),
    end: new Date("2024-11-19T00:00:00.000Z"),
    title: "Bascones, Candelle Vinace B. on Vacation Leave for 5.0 Day/s: VL",
    employee_number: "",
    name: "Bascones, Candelle Vinace B. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 46122,
    start: new Date("2024-11-12T00:00:00.000Z"),
    end: new Date("2024-11-15T00:00:00.000Z"),
    title: "Aquino, Patrick Hervic Cruz on Vacation Leave for 4.0 Day/s: VL hongkong race",
    employee_number: "",
    name: "Aquino, Patrick Hervic Cruz on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 50698,
    start: new Date("2024-11-10T00:00:00.000Z"),
    end: new Date("2024-11-11T00:00:00.000Z"),
    title: "Capal, Mary Jane De Leon on Vacation Leave for 1.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Capal, Mary Jane De Leon on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 55627,
    start: new Date("2024-11-09T00:00:00.000Z"),
    end: new Date("2024-11-10T00:00:00.000Z"),
    title: "Denoy, John Lloyd C. on Vacation Leave for 2.0 Day/s: Vecation Leave",
    employee_number: "",
    name: "Denoy, John Lloyd C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 56128,
    start: new Date("2024-11-08T00:00:00.000Z"),
    end: new Date("2024-11-09T00:00:00.000Z"),
    title: "Lumberio, Kimberly Daarol on Vacation Leave for 2.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Lumberio, Kimberly Daarol on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47691,
    start: new Date("2024-11-07T00:00:00.000Z"),
    end: new Date("2024-11-12T00:00:00.000Z"),
    title: "Jervoso, Ro Anne B. on Vacation Leave for 6.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Jervoso, Ro Anne B. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47332,
    start: new Date("2024-11-06T00:00:00.000Z"),
    end: new Date("2024-11-07T00:00:00.000Z"),
    title:
      "Narciso, Ria Marie B. on Vacation Leave for 2.0 Day/s: Vacation Leave Nov 6-7 / Approved by Kim during Midyear Meeting",
    employee_number: "",
    name: "Narciso, Ria Marie B. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47316,
    start: new Date("2024-11-06T00:00:00.000Z"),
    end: new Date("2024-11-06T00:00:00.000Z"),
    title: "Narciso, Ria Marie B. on Vacation Leave for 1.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Narciso, Ria Marie B. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 43196,
    start: new Date("2024-11-06T00:00:00.000Z"),
    end: new Date("2024-11-14T00:00:00.000Z"),
    title: "Santos, Raphael Daniel C. on Vacation Leave for 7.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Santos, Raphael Daniel C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47017,
    start: new Date("2024-11-05T00:00:00.000Z"),
    end: new Date("2024-11-05T00:00:00.000Z"),
    title: "Cabradilla, Daryl John C. on Vacation Leave for 1.0 Day/s: VL",
    employee_number: "",
    name: "Cabradilla, Daryl John C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 46121,
    start: new Date("2024-11-05T00:00:00.000Z"),
    end: new Date("2024-11-07T00:00:00.000Z"),
    title: "Aquino, Patrick Hervic Cruz on Vacation Leave for 3.0 Day/s: VL hongkong race",
    employee_number: "",
    name: "Aquino, Patrick Hervic Cruz on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 44962,
    start: new Date("2024-11-05T00:00:00.000Z"),
    end: new Date("2024-11-05T00:00:00.000Z"),
    title: "Santos, Raphael Daniel C. on Vacation Leave for 1.0 Day/s: VL",
    employee_number: "",
    name: "Santos, Raphael Daniel C. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47568,
    start: new Date("2024-11-04T00:00:00.000Z"),
    end: new Date("2024-11-05T00:00:00.000Z"),
    title: "Edoloverio, Jerrylyn P. on Vacation Leave for 2.0 Day/s: My Mothers Birthday",
    employee_number: "",
    name: "Edoloverio, Jerrylyn P. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 42612,
    start: new Date("2024-11-04T00:00:00.000Z"),
    end: new Date("2024-11-07T00:00:00.000Z"),
    title: "Recella, Allan Christopher Castor on Vacation Leave for 4.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Recella, Allan Christopher Castor on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 51505,
    start: new Date("2024-11-03T00:00:00.000Z"),
    end: new Date("2024-11-10T00:00:00.000Z"),
    title: "Tabunyag, Maria Angelica D. on Vacation Leave for 5.0 Day/s: Birthday",
    employee_number: "",
    name: "Tabunyag, Maria Angelica D. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47644,
    start: new Date("2024-11-02T00:00:00.000Z"),
    end: new Date("2024-11-03T00:00:00.000Z"),
    title: "Hernandez, Christian Joel S. on Vacation Leave for 2.0 Day/s: VL REQUEST",
    employee_number: "",
    name: "Hernandez, Christian Joel S. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47597,
    start: new Date("2024-11-02T00:00:00.000Z"),
    end: new Date("2024-11-03T00:00:00.000Z"),
    title:
      "Merlan, Shara Mae M. on Vacation Leave for 2.0 Day/s: Vacation Leave for special occassion",
    employee_number: "",
    name: "Merlan, Shara Mae M. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47003,
    start: new Date("2024-11-02T00:00:00.000Z"),
    end: new Date("2024-11-02T00:00:00.000Z"),
    title: "Pacheco, Perry Louie P. on Vacation Leave for 1.0 Day/s: Ice Cream Booth",
    employee_number: "",
    name: "Pacheco, Perry Louie P. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 46645,
    start: new Date("2024-11-02T00:00:00.000Z"),
    end: new Date("2024-11-03T00:00:00.000Z"),
    title: "Morales, Jasmine G. on Vacation Leave for 2.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Morales, Jasmine G. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 25703,
    start: new Date("2024-11-02T00:00:00.000Z"),
    end: new Date("2024-11-02T00:00:00.000Z"),
    title: "Special Holiday: All Souls’ Day",
    employee_number: "",
    name: "All Souls’ Day",
    holiday_type: "type_wpublic_holiday",
    category_ids: [2],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 56236,
    start: new Date("2024-11-01T00:00:00.000Z"),
    end: new Date("2024-11-01T00:00:00.000Z"),
    title: "Quiamno, Christine Cyril C. on Maternity Leave for 1.0 Day/s: t",
    employee_number: "",
    name: "Quiamno, Christine Cyril C. on Maternity Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 54967,
    start: new Date("2024-11-01T00:00:00.000Z"),
    end: new Date("2024-11-03T00:00:00.000Z"),
    title: "Reyes, Allyssa Marie Catigtig on Vacation Leave for 3.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Reyes, Allyssa Marie Catigtig on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 52437,
    start: new Date("2024-11-01T00:00:00.000Z"),
    end: new Date("2024-11-02T00:00:00.000Z"),
    title: "Manaois, Nelson Lopez on Vacation Leave for 2.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Manaois, Nelson Lopez on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 25698,
    start: new Date("2024-11-01T00:00:00.000Z"),
    end: new Date("2024-11-01T00:00:00.000Z"),
    title: "Special Holiday: All Saints’ Day",
    employee_number: "",
    name: "All Saints’ Day",
    holiday_type: "type_wpublic_holiday",
    category_ids: [2],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 51871,
    start: new Date("2024-10-31T00:00:00.000Z"),
    end: new Date("2024-10-31T00:00:00.000Z"),
    title: "Bedrijo, Margie L. on Vacation Leave for 1.0 Day/s: Vacation ",
    employee_number: "",
    name: "Bedrijo, Margie L. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47002,
    start: new Date("2024-10-31T00:00:00.000Z"),
    end: new Date("2024-10-31T00:00:00.000Z"),
    title: "Pacheco, Perry Louie P. on Vacation Leave for 1.0 Day/s: Ice Cream Booth",
    employee_number: "",
    name: "Pacheco, Perry Louie P. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 56232,
    start: new Date("2024-10-30T00:00:00.000Z"),
    end: new Date("2024-10-30T00:00:00.000Z"),
    title: "Quiamno, Christine Cyril C. on Maternity Leave for 1.0 Day/s: t",
    employee_number: "",
    name: "Quiamno, Christine Cyril C. on Maternity Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 50697,
    start: new Date("2024-10-30T00:00:00.000Z"),
    end: new Date("2024-10-30T00:00:00.000Z"),
    title: "Capal, Mary Jane De Leon on Vacation Leave for 1.0 Day/s: Vacation Leave ",
    employee_number: "",
    name: "Capal, Mary Jane De Leon on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47857,
    start: new Date("2024-10-30T00:00:00.000Z"),
    end: new Date("2024-10-31T00:00:00.000Z"),
    title: "Eser, John Wendel Aganan on Vacation Leave for 2.0 Day/s: VL OCT 30-31 2024",
    employee_number: "",
    name: "Eser, John Wendel Aganan on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 52855,
    start: new Date("2024-10-29T00:00:00.000Z"),
    end: new Date("2024-10-29T00:00:00.000Z"),
    title: "Dela Paz, Maria Carina M. on Vacation Leave for 1.0 Day/s: Vacation",
    employee_number: "",
    name: "Dela Paz, Maria Carina M. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47592,
    start: new Date("2024-10-29T00:00:00.000Z"),
    end: new Date("2024-10-30T00:00:00.000Z"),
    title: "Ortega, Joanna Marie Alpuerto on Vacation Leave for 2.0 Day/s: VACATION LEAVE",
    employee_number: "",
    name: "Ortega, Joanna Marie Alpuerto on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47591,
    start: new Date("2024-10-29T00:00:00.000Z"),
    end: new Date("2024-10-30T00:00:00.000Z"),
    title: "Martin, Benjamin Carl S. on Vacation Leave for 2.0 Day/s: Vacation Leave",
    employee_number: "",
    name: "Martin, Benjamin Carl S. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 47262,
    start: new Date("2024-10-29T00:00:00.000Z"),
    end: new Date("2024-10-30T00:00:00.000Z"),
    title:
      "Perdiguerra, John Roderick B. on Vacation Leave for 2.0 Day/s: Vacation Leave Bday of Perdi",
    employee_number: "",
    name: "Perdiguerra, John Roderick B. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 52769,
    start: new Date("2024-10-28T00:00:00.000Z"),
    end: new Date("2024-10-30T00:00:00.000Z"),
    title: "Liatona, Christine L. on Vacation Leave for 3.0 Day/s: Vacation",
    employee_number: "",
    name: "Liatona, Christine L. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
  {
    event_id: 52765,
    start: new Date("2024-10-28T00:00:00.000Z"),
    end: new Date("2024-10-29T00:00:00.000Z"),
    title: "Liatona, Christine L. on Vacation Leave for 2.0 Day/s: Vacation",
    employee_number: "",
    name: "Liatona, Christine L. on Vacation Leave",
    holiday_type: "",
    category_ids: [],
    work_email: "",
    allDay: true,
  },
];

export const generateRandomEvents = (total = 300) => {
  const events = [];
  for (let i = 0; i < total; i++) {
    const day = Math.round(i % 15);
    events.push({
      event_id: Math.random(),
      title: "Event " + (i + 1),
      start: new Date(
        new Date(new Date(new Date().setHours(10)).setMinutes(30)).setDate(
          new Date().getDate() + day
        )
      ),
      end: new Date(
        new Date(new Date(new Date().setHours(14)).setMinutes(0)).setDate(
          new Date().getDate() + day
        )
      ),
      // allDay: Math.random() > 0.5,
    });
  }

  return events;
};
